import { Class, Student } from '../types';

export const getInitialClasses = (): Class[] => [
    { id: 'CL001', name: 'Grade 10 - Section A', teacher: 'Mr. Harrison' },
    { id: 'CL002', name: 'Grade 10 - Section B', teacher: 'Ms. Wallace' },
    { id: 'CL003', name: 'Grade 11 - Science', teacher: 'Dr. Evelyn Reed' },
    { id: 'CL004', name: 'Grade 12 - Commerce', teacher: 'Mr. Peterson' },
];

export const getInitialStudents = (): Student[] => [
    {
        id: 'ST001',
        name: 'Liam Johnson',
        fatherName: 'Robert Johnson',
        motherName: 'Mary Johnson',
        class: 'Grade 10 - Section A',
        dob: '2009-05-15',
        gender: 'Male',
        type: 'Old Student',
        totalFees: 50000,
        feesPaid: 45000,
        paymentHistory: [
            { amount: 25000, date: '2025-04-10T10:00:00Z', receiptNumber: 'RCPT001', feesType: 'Tuition Fee', instrument: 'Cash' },
            { amount: 20000, date: '2025-07-15T11:30:00Z', receiptNumber: 'RCPT002', feesType: 'Tuition Fee', instrument: 'Online (UPI/NetBanking)', instrumentDetails: 'TXN12345' }
        ],
        transportNeeded: true,
        transportDetails: 'Bus Route 2, Stop B',
        contactNumber: '9876543210',
        hasPhoto: false,
    },
    {
        id: 'ST002',
        name: 'Olivia Smith',
        fatherName: 'James Smith',
        motherName: 'Patricia Smith',
        class: 'Grade 10 - Section A',
        dob: '2009-08-22',
        gender: 'Female',
        type: 'New Student',
        totalFees: 52000,
        feesPaid: 26000,
        paymentHistory: [
            { amount: 26000, date: '2025-04-12T09:00:00Z', receiptNumber: 'RCPT003', feesType: 'Admission Fee', instrument: 'Cheque', instrumentDetails: '123456' }
        ],
        transportNeeded: false,
        transportDetails: '',
        contactNumber: '9876543211',
        hasPhoto: false,
    },
    {
        id: 'ST003',
        name: 'Noah Williams',
        fatherName: 'John Williams',
        motherName: 'Jennifer Williams',
        class: 'Grade 11 - Science',
        dob: '2008-03-10',
        gender: 'Male',
        type: 'Old Student',
        totalFees: 55000,
        feesPaid: 55000,
        paymentHistory: [
            { amount: 27500, date: '2025-04-08T14:00:00Z', receiptNumber: 'RCPT004', feesType: 'Tuition Fee', instrument: 'Cash' },
            { amount: 27500, date: '2025-08-01T12:00:00Z', receiptNumber: 'RCPT005', feesType: 'Tuition Fee', instrument: 'Card (Debit/Credit)' }
        ],
        transportNeeded: true,
        transportDetails: 'Bus Route 1, Stop C',
        contactNumber: '9876543212',
        hasPhoto: false,
    },
    {
        id: 'ST004',
        name: 'Emma Brown',
        fatherName: 'Michael Brown',
        motherName: 'Linda Brown',
        class: 'Grade 12 - Commerce',
        dob: '2007-11-30',
        gender: 'Female',
        type: 'Old Student',
        totalFees: 60000,
        feesPaid: 30000,
        paymentHistory: [
            { amount: 30000, date: '2025-05-20T15:00:00Z', receiptNumber: 'RCPT006', feesType: 'Tuition Fee', instrument: 'Cash' }
        ],
        transportNeeded: false,
        transportDetails: '',
        contactNumber: '9876543213',
        hasPhoto: false,
    },
    {
        id: 'ST005',
        name: 'Ava Jones',
        fatherName: 'David Jones',
        motherName: 'Elizabeth Jones',
        class: 'Grade 10 - Section B',
        dob: '2009-09-05',
        gender: 'Female',
        type: 'New Student',
        totalFees: 52000,
        feesPaid: 0,
        paymentHistory: [],
        transportNeeded: true,
        transportDetails: 'Bus Route 3, Stop A',
        contactNumber: '9876543214',
        hasPhoto: false,
    },
    {
        id: 'ST006',
        name: 'Sophia Johnson',
        fatherName: 'Robert Johnson',
        motherName: 'Mary Johnson',
        class: 'Grade 12 - Commerce',
        dob: '2007-01-20',
        gender: 'Female',
        type: 'Old Student',
        totalFees: 60000,
        feesPaid: 60000,
        paymentHistory: [
            { amount: 30000, date: '2025-04-15T10:00:00Z', receiptNumber: 'RCPT007', feesType: 'Tuition Fee', instrument: 'Cash' },
            { amount: 30000, date: '2025-08-20T11:30:00Z', receiptNumber: 'RCPT008', feesType: 'Tuition Fee', instrument: 'Online (UPI/NetBanking)', instrumentDetails: 'TXN67890' }
        ],
        transportNeeded: true,
        transportDetails: 'Bus Route 2, Stop B',
        contactNumber: '9876543210',
        hasPhoto: false,
    },
];